package com.todo.todo.utils.enums;

public abstract class Values {
    
    public static final String REDIRECT_HOME_PAGE = "redirect:/users/home";
    public static final String ACCESS = "access";
    public static final String ERROR = "error";
    public static final String ID = "id";
    public static final String STRING = "string";
    public static final String DATA_STORAGE = "dataStorage";

    /*
     * EXCEPTIONS
     */

    public static final String ACCESS_DENIED = "Access denied for the user!";
    public static final String KEY_NOT_EXISTS = "No existing key = ";
    public static final String FIELD_EMPTY = "Empty field = ";

    /*
     * CATEGORY
     */

    public static final String CATEGORY = "category";
    public static final String CATEGORIES = "categories";
    public static final String CATEGORY_SELECTED = "categorySelected";
    public static final String CATEGORY_ERROR = "categoryError";

    public static final String TITLE_DEFAULT = "To do text category";
    public static final String TITLE = "title";
    public static final String TITLE_ERROR = "titleError";

    /*
     * TASK
     */

    public static final String TASK = "task";
    public static final String TASK_ERROR = "taskError";

    public static final String TEXT_DEFAULT = "Task text (autogenerated)";
    public static final String TEXT = "text";
    public static final String TEXT_ERROR = "textError";

    public static final String COMPLETED = "completed";

    /*
     * 
     */

}
